# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'IntelSpeaker' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'SnapKit'
  pod 'MBProgressHUD'
  pod 'IQKeyboardManagerSwift'

  # Pods for IntelSpeaker

end
